USE sistema_noleggio;
grant execute on procedure timbra to sn_cassiereè;
grant execute on procedure registraCliente to sn_cassiereè;
grant execute on procedure listaClienti to sn_cassiereè;
grant execute on procedure rimuoviCliente to sn_cassiereè;
grant execute on procedure inserisciRecapitiCliente to sn_cassiereè;
grant execute on procedure rimuoviRecapitiCliente to sn_cassiereè;
grant execute on procedure registraNoleggio to sn_cassiereè;
grant execute on procedure registraRestituzione to sn_cassiereè;
grant execute on procedure listaNoleggiCorrenti to sn_cassiereè;
grant execute on procedure listaNoleggiScaduti to sn_cassiereè;
grant execute on procedure listaNoleggiCopiaFilm to sn_cassiereè;
grant execute on procedure listaNoleggiCliente to sn_cassiereè;
grant execute on procedure listaNoleggiFilm to sn_cassiereè;
FLUSH PRIVILEGES;