USE sistema_noleggio;
grant execute on procedure registraImpiegato to sn_proprietario@localhost;
grant execute on procedure modificaCarica to sn_proprietario@localhost;
grant execute on procedure inserisciTurnoLavoro to sn_proprietario@localhost;
grant execute on procedure reportMensile to sn_proprietario@localhost;
grant execute on procedure reportAnnuale to sn_proprietario@localhost;
grant execute on procedure rimuoviImpiegato to sn_proprietario@localhost;
grant execute on procedure rimuoviTurnoLavoro to sn_proprietario@localhost;
grant execute on procedure listaImpiegati to sn_proprietario@localhost;
grant execute on procedure inserisciFilm to sn_proprietario@localhost;
grant execute on procedure listaFilm to sn_proprietario@localhost;
grant execute on procedure rimuoviFilm to sn_proprietario@localhost;
grant execute on procedure listaTurni to sn_proprietario@localhost;
grant execute on procedure inserisciSettore to sn_proprietario@localhost;
grant execute on procedure listaSettori to sn_proprietario@localhost;
grant execute on procedure rimuoviSettore to sn_proprietario@localhost;
grant execute on procedure inserisciCopiaFilm to sn_proprietario@localhost;
grant execute on procedure listaCopieFilm to sn_proprietario@localhost;
grant execute on procedure rimuoviCopiaFilm to sn_proprietario@localhost;
grant execute on procedure listaCariche to sn_proprietario@localhost;
FLUSH PRIVILEGES;