INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Ben-Hur', 'Fred Niblo', 'Francis', 'X. Bushman');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Ben-Hur', 'Fred Niblo', 'Ramon', 'Novarro');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Ben-Hur', 'William Wyler', 'Charlton', 'Heston');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Ben-Hur', 'William Wyler', 'Jack', 'Hawkins');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Cape Fear', 'J. Lee Thompson', 'Gregory', 'Peck');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Cape Fear', 'J. Lee Thompson', 'Robert', 'Mitchum');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Cape Fear', 'Martin Scorsese', 'Nick', 'Nolte');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Cape Fear', 'Martin Scorsese', 'Robert', 'De Niro');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Fight Club', 'David Fincher', 'Brad', 'Pitt');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Fight Club', 'David Fincher', 'Edward', 'Norton');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Forrest Gump', 'Robert Zemeckis', 'Robin', 'Wright');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Forrest Gump', 'Robert Zemeckis', 'Tom', 'Hanks');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Il Padrino', 'Francis Ford Coppola', 'Al', 'Pacino');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Il Padrino', 'Francis Ford Coppola', 'Marlon', 'Brando');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Inception', 'Christopher Nolan', 'Joseph', 'Gordon-Levitt');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Inception', 'Christopher Nolan', 'Leonardo', 'DiCaprio');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Interstellar', 'Christopher Nolan', 'Anne', 'Hathaway');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Interstellar', 'Christopher Nolan', 'Matthew', 'McConaughey');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('King Kong', 'Merian C. Cooper, Ernest B. Schoedsack', 'Fay', 'Wray');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('King Kong', 'Merian C. Cooper, Ernest B. Schoedsack', 'Robert', 'Armstrong');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('King Kong', 'Peter Jackson', 'Jack', 'Black');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('King Kong', 'Peter Jackson', 'Naomi', 'Watts');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('La vita è bella', 'Roberto Benigni', 'Nicoletta', 'Braschi');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('La vita è bella', 'Roberto Benigni', 'Roberto', 'Benigni');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Ocean\'s Eleven', 'Lewis Milestone', 'Dean', 'Martin');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Ocean\'s Eleven', 'Lewis Milestone', 'Frank', 'Sinatra');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Ocean\'s Eleven', 'Steven Soderbergh', 'Brad', 'Pitt');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Ocean\'s Eleven', 'Steven Soderbergh', 'George', 'Clooney');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Pulp Fiction', 'Quentin Tarantino', 'John', 'Travolta');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Pulp Fiction', 'Quentin Tarantino', 'Uma', 'Thurman');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Scarface', 'Brian De Palma', 'Al', 'Pacino');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Scarface', 'Brian De Palma', 'Michelle', 'Pfeiffer');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Scarface', 'Howard Hawks, Richard Rosson', 'Ann', 'Dvorak');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Scarface', 'Howard Hawks, Richard Rosson', 'Paul', 'Muni');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Schindler\'s List', 'Steven Spielberg', 'Ben', 'Kingsley');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('Schindler\'s List', 'Steven Spielberg', 'Liam', 'Neeson');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Departed', 'Andrew Lau, Alan Mak', 'Andy', 'Lau');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Departed', 'Andrew Lau, Alan Mak', 'Tony', 'Leung');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Departed', 'Martin Scorsese', 'Leonardo', 'DiCaprio');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Departed', 'Martin Scorsese', 'Matt', 'Damon');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Fly', 'David Cronenberg', 'Geena', 'Davis');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Fly', 'David Cronenberg', 'Jeff', 'Goldblum');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Fly', 'Kurt Neumann', 'David', 'Hedison');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Fly', 'Kurt Neumann', 'Vincent', 'Price');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Godfather: Part II', 'Francis Ford Coppola', 'Al', 'Pacino');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Godfather: Part II', 'Francis Ford Coppola', 'Robert', 'De Niro');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Italian Job', 'F. Gary Gray', 'Charlize', 'Theron');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Italian Job', 'F. Gary Gray', 'Mark', 'Wahlberg');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Italian Job', 'Peter Collinson', 'Michael', 'Caine');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Italian Job', 'Peter Collinson', 'Noel', 'Coward');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Shawshank Redemption', 'Frank Darabont', 'Morgan', 'Freeman');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Shawshank Redemption', 'Frank Darabont', 'Tim', 'Robbins');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Thing', 'John Carpenter', 'Kurt', 'Russell');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Thing', 'John Carpenter', 'Wilford', 'Brimley');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Thing from Another World', 'Christian Nyby, Howard Hawks', 'Kenneth', 'Tobey');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('The Thing from Another World', 'Christian Nyby, Howard Hawks', 'Margaret', 'Sheridan');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('True Grit', 'Henry Hathaway', 'Glen', 'Campbell');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('True Grit', 'Henry Hathaway', 'John', 'Wayne');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('True Grit', 'Joel and Ethan Coen', 'Hailee', 'Steinfeld');
INSERT INTO sistema_noleggio.cast_film (film_titolo, film_regista, attore_nome, attore_cognome) VALUES ('True Grit', 'Joel and Ethan Coen', 'Jeff', 'Bridges');
