INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (1, 'Forrest Gump', 'Robert Zemeckis', 'DVD', 7, 'A1');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (2, 'Forrest Gump', 'Robert Zemeckis', 'DVD', 7, 'A2');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (3, 'Forrest Gump', 'Robert Zemeckis', 'Videocassetta', 7, 'A3');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (4, 'Forrest Gump', 'Robert Zemeckis', 'DVD', 7, 'A4');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (5, 'Forrest Gump', 'Robert Zemeckis', 'Videocassetta', 7, 'A5');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (6, 'Il Padrino', 'Francis Ford Coppola', 'DVD', 3, 'C2');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (7, 'Il Padrino', 'Francis Ford Coppola', 'DVD', 3, 'C3');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (8, 'Il Padrino', 'Francis Ford Coppola', 'Videocassetta', 3, 'C4');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (9, 'Il Padrino', 'Francis Ford Coppola', 'Videocassetta', 3, 'C5');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (10, 'Il Padrino', 'Francis Ford Coppola', 'DVD', 3, 'C6');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (11, 'Pulp Fiction', 'Quentin Tarantino', 'Videocassetta', 10, 'E7');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (12, 'Pulp Fiction', 'Quentin Tarantino', 'DVD', 10, 'E8');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (13, 'Pulp Fiction', 'Quentin Tarantino', 'DVD', 10, 'E9');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (14, 'Pulp Fiction', 'Quentin Tarantino', 'Videocassetta', 10, 'E10');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (15, 'Pulp Fiction', 'Quentin Tarantino', 'DVD', 10, 'E11');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (16, 'Interstellar', 'Christopher Nolan', 'DVD', 2, 'G9');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (17, 'Interstellar', 'Christopher Nolan', 'DVD', 2, 'G10');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (18, 'Interstellar', 'Christopher Nolan', 'Videocassetta', 2, 'G11');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (19, 'Interstellar', 'Christopher Nolan', 'DVD', 2, 'G12');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (20, 'Interstellar', 'Christopher Nolan', 'DVD', 2, 'G13');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (21, 'La vita è bella', 'Roberto Benigni', 'DVD', 9, 'I3');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (22, 'La vita è bella', 'Roberto Benigni', 'DVD', 9, 'I4');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (23, 'La vita è bella', 'Roberto Benigni', 'Videocassetta', 9, 'I5');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (24, 'La vita è bella', 'Roberto Benigni', 'DVD', 9, 'I6');
INSERT INTO sistema_noleggio.copia_film (codice, titolo, regista, tipo, settore, posizione) VALUES (25, 'La vita è bella', 'Roberto Benigni', 'Videocassetta', 9, 'I7');
